# Generated by Django 4.0.5 on 2022-06-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IM_service', '0004_suppliers_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sub_categoryes',
            name='s_category_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
