# Generated by Django 4.0.5 on 2022-06-09 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IM_service', '0011_alter_products_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='IM_service.store'),
        ),
    ]
