# Generated by Django 4.0.5 on 2022-06-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IM_servise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_id',
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
