# Generated by Django 4.0.5 on 2022-06-07 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IM_servise', '0002_alter_categories_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_store', models.CharField(max_length=20)),
                ('address_store', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Categoryes',
            fields=[
                ('s_category_id', models.SmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('s_category_name', models.CharField(max_length=20)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='IM_servise.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=60)),
                ('barcode', models.IntegerField(unique=True)),
                ('quantity', models.SmallIntegerField(blank=True)),
                ('unit_price', models.IntegerField()),
                ('sale_price', models.IntegerField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='IM_servise.categories')),
                ('s_category_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='IM_servise.sub_categoryes')),
            ],
        ),
    ]
