# Generated by Django 4.0.5 on 2022-06-08 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IM_servise', '0003_store_sub_categoryes_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplier_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='sub_categoryes',
            options={'verbose_name': 'Sub_Category', 'verbose_name_plural': 'Sub_categories'},
        ),
        migrations.AlterField(
            model_name='products',
            name='barcode',
            field=models.IntegerField(max_length=13, unique=True),
        ),
        migrations.AddField(
            model_name='products',
            name='supplier_id',
            field=models.ForeignKey(default=3145, on_delete=django.db.models.deletion.DO_NOTHING, to='IM_servise.suppliers'),
            preserve_default=False,
        ),
    ]
