# Generated by Django 4.0.5 on 2022-06-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IM_servise', '0005_alter_categories_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_categoryes',
            name='s_category_name',
            field=models.CharField(max_length=30),
        ),
    ]
