# Generated by Django 4.0.5 on 2022-06-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IM_servise', '0006_alter_sub_categoryes_s_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_categoryes',
            name='s_category_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
