# Generated by Django 4.0.5 on 2022-06-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IM_servise', '0008_alter_categories_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='barcode',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
