# Generated by Django 4.0.5 on 2022-06-09 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IM_servise', '0009_alter_products_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='store_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='IM_servise.store'),
            preserve_default=False,
        ),
    ]
